### ISSUE TITLE
Example 1

### ISSUE THREAD

**Issue by tlylt** [tlylt/coded-clique#1]
<details>
<summary>IkhpIFwiaGVsbG9cIiwgd29ybGQsIGB0aGlzIGlzIGNvZGVgXHJcbmBgYFxyXG5uaWNlICBcclxuXCJxdW90ZSBpbiBjb2RlXCJcclxuYGBgIg==

█▀▀ █▀█ █▀▄ █▀▀ █▀▄   █▀▀ █░░ █ █▀█ █░█ █▀▀
█▄▄ █▄█ █▄▀ ██▄ █▄▀   █▄▄ █▄▄ █ ▀▀█ █▄█ ██▄
</summary>

---

<details>
  <summary>PGRldGFpbHM+CiAgPHN1bW1hcnk+V2hhdCBkbyB5b3UgbGlrZSB0byBkbyBmb3IgZnVuPwoK4paI4paA4paA4oCD4paI4paA4paI4oCD4paI4paA4paE4oCD4paI4paA4paA4oCD4paI4paA4paE4oCDIOKAg+KWiOKWgOKWgOKAg+KWiOKWkeKWkeKAg+KWiOKAg+KWiOKWgOKWiOKAg+KWiOKWkeKWiOKAg+KWiOKWgOKWgArilojiloTiloTigIPilojiloTilojigIPilojiloTiloDigIPilojilojiloTigIPilojiloTiloDigIMg4oCD4paI4paE4paE4oCD4paI4paE4paE4oCD4paI4oCD4paA4paA4paI4oCD4paI4paE4paI4oCD4paI4paI4paECiAgPC9zdW1tYXJ5PgoKLS0tCgpUaGlzIGlzc3VlIGRlbW9uc3RyYXRlcyB0aGUgcmVzdWx0IG9mIHVzaW5nIA0KDQoKPC9kZXRhaWxzPgo=

█▀▀ █▀█ █▀▄ █▀▀ █▀▄   █▀▀ █░░ █ █▀█ █░█ █▀▀
█▄▄ █▄█ █▄▀ ██▄ █▄▀   █▄▄ █▄▄ █ ▀▀█ █▄█ ██▄
  </summary>

---

<details>
  <summary>What do you like to do for fun?

█▀▀ █▀█ █▀▄ █▀▀ █▀▄   █▀▀ █░░ █ █▀█ █░█ █▀▀
█▄▄ █▄█ █▄▀ ██▄ █▄▀   █▄▄ █▄▄ █ ▀▀█ █▄█ ██▄
  </summary>

---

This issue demonstrates the "result" of using `encoding: question`

```
      - name: coded-clique
        uses: tlylt/coded-clique@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          encoding: question
```
</details>

</details>

</details>
