### ISSUE TITLE
World

### ISSUE THREAD

**Issue by tlylt** [tlylt/coded-clique#3]
<details>
  <summary>SG93IGFyZSB5b3U/

█▀▀ █▀█ █▀▄ █▀▀ █▀▄   █▀▀ █░░ █ █▀█ █░█ █▀▀
█▄▄ █▄█ █▄▀ ██▄ █▄▀   █▄▄ █▄▄ █ ▀▀█ █▄█ ██▄
  </summary>

---

How are you?
</details>

**Comment by tlylt** [comment]
This issue demonstrates the "result" of using `encoding: rot13`

```
      - name: coded-clique
        uses: tlylt/coded-clique@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          encoding: "rot13"
```
